site_name: Akhil T Muralidharan

theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
language: en
palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
    primary: teal
    accent: purple
  - scheme: default
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
    primary: teal
    accent: lime
extra: 
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/akhil4chelsia
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/akhiltm/
    - icon: fontawesome/brands/wordpress
      link: https://akhilt.wordpress.com/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences 
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://www.linkedin.com/in/akhiltm/" target="_blank" rel="noopener"> Akhil T Muralidharan </a>